#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================
#==================================================================================================
name: FinanceApp
#==================================================================================================
settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  xcodeVersion: "12.4"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "14.2"

#==================================================================================================
targets:
#==================================================================================================
  FinanceApp:
    platform: iOS
    type: application
    
    sources:
      - path: FinanceApp
  
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.devpass.FinanceApp
      INFOPLIST_FILE: FinanceApp/Resources/Info.plist
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PROVISIONING_PROFILE: "Wildcard"
      
      ENABLE_BITCODE: "NO"
      TARGETED_DEVICE_FAMILY: "1"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
      ARCHS: $(ARCHS_STANDARD)
  
  #____________________________________________________________
  # Tests

  FinanceAppTests:

    platform: iOS
    type: bundle.unit-test

    sources:
      - path: FinanceAppTests
    
    dependencies:
      - target: FinanceApp
    
#==================================================================================================
schemes:
#==================================================================================================

  FinanceApp:
    build:
      targets:
        FinanceApp: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - FinanceApp
      targets:
        - FinanceAppTests

#==================================================================================================